version: "3.9"

services:
  collection:
    image: collection:latest
    build:
      context: ${PWD}/collection
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Running Collection Backend' && \
      python main.py"
    volumes:
      - ${PWD}/collection/app:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      collection_database:
        condition: service_healthy
    expose:
      - ${COLLECTION_PORT}
    networks:
      - like_network
    restart: unless-stopped
