version: "3.9"

services:
  poker_collection_tests:
    image: poker_collection_tests:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run tests' && \
      python -m pytest --capture=sys --cov=app --cov-report html tests"
    volumes:
      - ${PWD}/:/app
    env_file:
      - ${PWD}/.env
    environment:
      DATABASE_HOSTNAME: poker_collection_tests_database
    depends_on:
      poker_collection_tests_database:
        condition: service_healthy
